language: node_js
node_js:
  - 'node'
  - '8'
before_install:
  - npm i -g greenkeeper-lockfile@1 coveralls mocha-lcov-reporter
before_script:
  - npm run update
  - greenkeeper-lockfile-update
script:
  - npm run test && npx nyc report --reporter=text-lcov | coveralls
