language: node_js
node_js:
  - 'node'
  - '8'
before_install:
  - npm i -D greenkeeper-lockfile@1
  - npm i -D coveralls
  - npm i -D mocha-lcov-reporter
before_script:
  - npx greenkeeper-lockfile-update
script:
  - npm run test && npx nyc report --reporter=text-lcov | npx coveralls
